BANKS = [
    ("TCB", "tcb.png"),
    ("ACB", "acb.png"),
    ("VCB", "vcb.png"),
    ("MB", "mb.png"),
    ("MSB", "msb.png"),
    ("VTB", "vtb.png"),
    ("OCB", "ocb.png"),
    ("VPBANK", "vpbank.png"),
    ("Eximbank", "eximbank.png"),
    ("BIDV", "bidv.png"),
    ("VIB", "vib.png"),
    ("SACOMBANK", "sacombank.png"),
    ("SHB", "shb.png"),
    ("VIETBANK", "vietbank.png"),
    ("PVCOMBANK", "pvcombank.png"),
    ("NCB", "ncb.png"),
    ("PGBANK", "pgbank.png"),
    ("NAMABANK", "namabank.png"),
    ("LPbank", "lpbank.png"),
    ("HDbank", "hdbank.png"),
    ("Vikki", "vikki.png"),
    ("KIENLONGBANK", "kienlongbank.png"),
    ("Bản Việt", "banviet.png"),
    ("SAIGONBANK", "saigonbank.png"),
    ("ABBANK", "abbank.png"),
    ("VietABank", "vietabank.png"),
    ("vietconbank neo", "vietconbank_neo.png"),
    ("mbv", "mbv.png"),
]